language: python

python: 2.7

install:
  - pip install cx_freeze

script:
  - python setup.py build --build-exe bin
  - pip uninstall pytest -y
  - zip -l bin/library.zip # debug
  - bin/runtests --pytest --verbose tests