language: python

python: 2.7

install:
  - pip install cx_freeze
  - pip install --upgrade pytest

script:
  - python setup.py build --build-exe bin
  - pip uninstall pytest -y
  - unzip -l bin/library.zip # debug
  - bin/runtests --pytest --verbose tests