language: python

python: 2.7

install:
  - sudo apt-get install python-dev
  - pip install cx_freeze
  - pip install --upgrade pytest

script:
  - python setup.py build --build-exe bin
  - pip uninstall pytest -y
  - unzip -l bin/library.zip # debug
  - cd bin
  - ./runtests --pytest --verbose tests